import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

// 1. This file is generated by the FlutterFire CLI
import 'firebase_options.dart';

// 2. The new entry point for your app
import 'screens/role_selection_screen.dart';

void main() async {
  // Ensure that Flutter bindings are initialized before calling Firebase
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase with the platform-specific options
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const TailorHubApp());
}

class TailorHubApp extends StatelessWidget {
  const TailorHubApp({super.key});

  @override
  Widget build(BuildContext context) {
    // Define the consistent color palette for the app's theme
    const Color backgroundColor = Color(0xFFF7F2E9); // Natural Khadi/Silk
    const Color primaryTextColor = Color(0xFF2C3A4F); // Deep Indigo
    const Color accentColor = Color(0xFFE5A12D);     // Warm Marigold/Ochre

    return MaterialApp(
      title: 'TailorHub',
      debugShowCheckedModeBanner: false,

      // --- Define the global theme for the entire app ---
      theme: ThemeData(
        scaffoldBackgroundColor: backgroundColor,
        primaryColor: primaryTextColor,

        // Define default text styles using Google Fonts
        textTheme: GoogleFonts.latoTextTheme(Theme.of(context).textTheme),

        // Define a consistent style for AppBars
        appBarTheme: AppBarTheme(
          backgroundColor: backgroundColor,
          elevation: 0,
          iconTheme: const IconThemeData(color: primaryTextColor),
          titleTextStyle: GoogleFonts.playfairDisplay(
            color: primaryTextColor,
            fontSize: 22,
            fontWeight: FontWeight.bold,
          ),
        ),

        // Define a consistent style for ElevatedButtons
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: primaryTextColor, // Indigo button
            foregroundColor: backgroundColor, // Light text
            elevation: 0,
            padding: const EdgeInsets.symmetric(vertical: 16),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
            textStyle: GoogleFonts.lato(
              fontSize: 18,
              fontWeight: FontWeight.bold,
            ),
          ),
        ),
      ),

      // 3. Set the home screen to the new role selection page
      home: const RoleSelectionScreen(),
    );
  }
}